### ISSUE TITLE
PowerUp timer doesn't show up with every powerup

### ISSUE THREAD

**Issue by bw-davis** [snelson3/Happy-Yarnball#53] opened 2016-05-26 23:48 UTC

**Comment by bw-davis** [comment] 2016-05-27 00:09
So this is really really a weird one.  Sometimes it will display and sometimes not.  For certain objects it never displays.  But for instance if you get the third speed up in ocean level without touching the first one it will display.  If you get the first one it will display that.  But it never displays on the second double jump powerup

**Comment by snelson3** [comment] 2016-05-27 05:11
The problem is this code in updateController's Update() function

`if (Time.time > durationTime)
            timeText.text = "";`

This was intended to make the timer blank when the upgrade was done, but when there's multiple instances of each upgrade they are overwriting each other. 

Fix might be a public shared durationTime between instances of each type of upgrade. Or moving this code into PlayerController or GameController.

**Comment by snelson3** [comment] 2016-05-27 05:20
fixed, easy problem I'm silly

**Closed as completed by snelson3** 2016-05-27 05:20 UTC
